### ISSUE TITLE
Thanks for your sharing

### ISSUE THREAD

**Issue by TrumanZYX** [Rick-Chen-PKU/Depression_GI#1]
Dear Chen,
  Thanks for your sharing, the code is very interesting and good. Can you tell me the paper name? Because i want to reanalysis to learn the MR, but i search the paper and do not find it.
  Or can you provide the exposure and outcome data url. Thanks for your help.

**Comment by Rick-Chen-PKU** [comment]
Our article is currently unpublished. You can leave an email and I will provide the URL for exposure and outcome data

**Comment by TrumanZYX** [comment]
Thanks for your help. My email is zhuyuexin96@163.com /  zhuyuexin96@ccmu.edu.cn.
  Thanks
